#! /opt/conda/bin/Rscript

library("argparse")
parser <- ArgumentParser()
parser$add_argument("-n","--name",default="代谢通路富集表.xlsx", help="文件名")
parser$add_argument("-t","--type",default="jpg", help="图片格式")
parser$add_argument("-nu","--number",default=10, type="integer",help="通路最多可视化数量")

args <- parser$parse_args()

RMETA2::auto_alldraw(name = args$name,
needgroup="R_N",
type = args$type,
needlist=c("Annotation","in set","p-value","RichFactor"),
range=1:args$number,
drawwhat = "bubblechart")