#! /opt/conda/bin/Rscript
library("argparse")
parser <- ArgumentParser()
parser$add_argument("-s","--species",default="ko", help="物种")
parser$add_argument("-t","--timeout",default=0, help="超时")
args <- parser$parse_args()

RMETA2::downloadkegg(
species=args$species,
overwrite = T,
timeout=args$timeout
)

